// src\lib\constants\locations.ts
export const COUNTRY = 'Philippines';

export const REGIONS = [
  {
    id: 'region-1',
    name: 'Ilocos Region (Region I)',
    provinces: [
      {
        id: 'province-1',
        name: 'Ilocos Norte',
        citiesMunicipalities: [
          'Adams',
          'Bacarra',
          'Badoc',
          'Bangui',
          'Banna',
          'Batac City',
          'Burgos',
          'Carasi',
          'Currimao',
          'Dingras',
          'Dumalneg',
          'Laoag City',
          'Marcos',
          'Nueva Era',
          'Pagudpud',
          'Paoay',
          'Pasuquin',
          'Piddig',
          'Pinili',
          'San Nicolas',
          'Sarrat',
          'Solsona',
          'Vintar',
        ],
      },
      {
        id: 'province-2',
        name: 'Ilocos Sur',
        citiesMunicipalities: [
          'Alilem',
          'Banayoyo',
          'Bantay',
          'Burgos',
          'Cabugao',
          'Candon City',
          'Caoayan',
          'Cervantes',
          'Galimuyod',
          'Gregorio del Pilar',
          'Lidlidda',
          'Magsingal',
          'Nagbukel',
          'Narvacan',
          'Quirino',
          'Salcedo',
          'San Emilio',
          'San Esteban',
          'San Ildefonso',
          'San Juan',
          'San Vicente',
          'Santa',
          'Santa Catalina',
          'Santa Cruz',
          'Santa Lucia',
          'Santa Maria',
          'Santiago',
          'Santo Domingo',
          'Sigay',
          'Sinait',
          'Sugpon',
          'Suyo',
          'Tagudin',
          'Vigan City',
        ],
      },
      {
        id: 'province-3',
        name: 'La Union',
        citiesMunicipalities: [
          'Agoo',
          'Aringay',
          'Bacnotan',
          'Bagulin',
          'Balaoan',
          'Bangar',
          'Bauang',
          'Burgos',
          'Caba',
          'Luna',
          'Naguilian',
          'Pugo',
          'Rosario',
          'San Fernando City',
          'San Gabriel',
          'San Juan',
          'Santo Tomas',
          'Santol',
          'Sudipen',
          'Tubao',
        ],
      },
      {
        id: 'province-4',
        name: 'Pangasinan',
        citiesMunicipalities: [
          'Agno',
          'Aguilar',
          'Alaminos City',
          'Alcala',
          'Anda',
          'Asingan',
          'Balungao',
          'Bani',
          'Basista',
          'Bautista',
          'Bayambang',
          'Binalonan',
          'Binmaley',
          'Bolinao',
          'Bugallon',
          'Burgos',
          'Calasiao',
          'Dagupan City',
          'Dasol',
          'Infanta',
          'Labrador',
          'Laoac',
          'Lingayen',
          'Mabini',
          'Malasiqui',
          'Manaoag',
          'Mangaldan',
          'Mangatarem',
          'Mapandan',
          'Natividad',
          'Pozorrubio',
          'Rosales',
          'San Carlos City',
          'San Fabian',
          'San Jacinto',
          'San Manuel',
          'San Nicolas',
          'San Quintin',
          'Santa Barbara',
          'Santa Maria',
          'Santo Tomas',
          'Sison',
          'Sual',
          'Tayug',
          'Umingan',
          'Urbiztondo',
          'Urdaneta City',
          'Villasis',
        ],
      },
    ],
  },
  {
    id: 'region-2',
    name: 'Cagayan Valley (Region II)',
    provinces: [
      {
        id: 'province-1',
        name: 'Batanes',
        citiesMunicipalities: [
          'Basco',
          'Itbayat',
          'Ivana',
          'Mahatao',
          'Sabtang',
          'Uyugan',
        ],
      },
      {
        id: 'province-2',
        name: 'Cagayan',
        citiesMunicipalities: [
          'Abulug',
          'Alcala',
          'Allacapan',
          'Amulung',
          'Aparri',
          'Baggao',
          'Ballesteros',
          'Buguey',
          'Calayan',
          'Camalaniugan',
          'Claveria',
          'Enrile',
          'Gattaran',
          'Gonzaga',
          'Iguig',
          'Lal-lo',
          'Lasam',
          'Pamplona',
          'Peñablanca',
          'Piat',
          'Rizal',
          'Sanchez-Mira',
          'Santa Ana',
          'Santa Praxedes',
          'Santa Teresita',
          'Santo Niño',
          'Solana',
          'Tuao',
          'Tuguegarao City',
        ],
      },
      {
        id: 'province-3',
        name: 'Isabela',
        citiesMunicipalities: [
          'Alicia',
          'Angadanan',
          'Aurora',
          'Benito Soliven',
          'Burgos',
          'Cabagan',
          'Cabatuan',
          'Cauayan City',
          'Cordon',
          'Dinapigue',
          'Divilacan',
          'Echague',
          'Gamu',
          'Ilagan City',
          'Jones',
          'Luna',
          'Maconacon',
          'Mallig',
          'Naguilian',
          'Palanan',
          'Quezon',
          'Quirino',
          'Ramon',
          'Reina Mercedes',
          'Roxas',
          'San Agustin',
          'San Guillermo',
          'San Isidro',
          'San Manuel',
          'San Mariano',
          'San Mateo',
          'San Pablo',
          'Santa Maria',
          'Santiago City',
          'Santo Tomas',
          'Tumauini',
        ],
      },
      {
        id: 'province-4',
        name: 'Nueva Vizcaya',
        citiesMunicipalities: [
          'Alfonso Castañeda',
          'Ambaguio',
          'Aritao',
          'Bagabag',
          'Bambang',
          'Bayombong',
          'Diadi',
          'Dupax del Norte',
          'Dupax del Sur',
          'Kasibu',
          'Kayapa',
          'Quezon',
          'Santa Fe',
          'Solano',
          'Villaverde',
        ],
      },
      {
        id: 'province-5',
        name: 'Quirino',
        citiesMunicipalities: [
          'Aglipay',
          'Cabarroguis',
          'Diffun',
          'Maddela',
          'Nagtipunan',
          'Saguday',
        ],
      },
    ],
  },
  {
    id: 'region-3',
    name: 'Central Luzon (Region III)',
    provinces: [
      {
        id: 'province-1',
        name: 'Aurora',
        citiesMunicipalities: [
          'Baler',
          'Casiguran',
          'Dilasag',
          'Dinalungan',
          'Dipaculao',
          'Maria Aurora',
          'San Luis',
        ],
      },
      {
        id: 'province-2',
        name: 'Bataan',
        citiesMunicipalities: [
          'Abucay',
          'Bagac',
          'Balanga City',
          'Dinalupihan',
          'Hermosa',
          'Limay',
          'Mariveles',
          'Morong',
          'Orani',
          'Orion',
          'Pilar',
          'Samal',
        ],
      },
      {
        id: 'province-3',
        name: 'Bulacan',
        citiesMunicipalities: [
          'Angat',
          'Balagtas',
          'Baliuag',
          'Bocaue',
          'Bulakan',
          'Bustos',
          'Calumpit',
          'Doña Remedios Trinidad',
          'Guiguinto',
          'Hagonoy',
          'Malolos City',
          'Marilao',
          'Meycauayan City',
          'Norzagaray',
          'Obando',
          'Pandi',
          'Paombong',
          'Plaridel',
          'Pulilan',
          'San Ildefonso',
          'San Jose del Monte City',
          'San Miguel',
          'San Rafael',
          'Santa Maria',
        ],
      },
      {
        id: 'province-4',
        name: 'Nueva Ecija',
        citiesMunicipalities: [
          'Aliaga',
          'Bongabon',
          'Cabanatuan City',
          'Cabiao',
          'Carranglan',
          'Cuyapo',
          'Gabaldon',
          'Gapan City',
          'General Mamerto Natividad',
          'General Tinio',
          'Guimba',
          'Jaen',
          'Laur',
          'Licab',
          'Llanera',
          'Lupao',
          'Muñoz City',
          'Nampicuan',
          'Palayan City',
          'Pantabangan',
          'Peñaranda',
          'Quezon',
          'Rizal',
          'San Antonio',
          'San Isidro',
          'San Jose City',
          'San Leonardo',
          'Santa Rosa',
          'Santo Domingo',
          'Talavera',
          'Talugtug',
          'Zaragoza',
        ],
      },
      {
        id: 'province-5',
        name: 'Pampanga',
        citiesMunicipalities: [
          'Angeles City',
          'Apalit',
          'Arayat',
          'Bacolor',
          'Candaba',
          'Floridablanca',
          'Guagua',
          'Lubao',
          'Mabalacat City',
          'Macabebe',
          'Magalang',
          'Masantol',
          'Mexico',
          'Minalin',
          'Porac',
          'San Fernando City',
          'San Luis',
          'San Simon',
          'Santa Ana',
          'Santa Rita',
          'Santo Tomas',
          'Sasmuan',
        ],
      },
      {
        id: 'province-6',
        name: 'Tarlac',
        citiesMunicipalities: [
          'Anao',
          'Bamban',
          'Camiling',
          'Capas',
          'Concepcion',
          'Gerona',
          'La Paz',
          'Mayantoc',
          'Moncada',
          'Paniqui',
          'Pura',
          'Ramos',
          'San Clemente',
          'San Jose',
          'San Manuel',
          'Santa Ignacia',
          'Tarlac City',
          'Victoria',
        ],
      },
      {
        id: 'province-7',
        name: 'Zambales',
        citiesMunicipalities: [
          'Botolan',
          'Cabangan',
          'Candelaria',
          'Castillejos',
          'Iba',
          'Masinloc',
          'Olongapo City',
          'Palauig',
          'San Antonio',
          'San Felipe',
          'San Marcelino',
          'San Narciso',
          'Santa Cruz',
          'Subic',
        ],
      },
    ],
  },
  {
    id: 'region-4',
    name: 'Calabarzon (Region IV-A) and Mimaropa (Region IV-B)',
    provinces: [
      {
        id: 'province-1',
        name: 'Batangas',
        citiesMunicipalities: [
          'Agoncillo',
          'Alitagtag',
          'Balayan',
          'Balete',
          'Batangas City',
          'Bauan',
          'Calaca',
          'Calatagan',
          'Cuenca',
          'Ibaan',
          'Laurel',
          'Lemery',
          'Lian',
          'Lipa City',
          'Lobo',
          'Mabini',
          'Malvar',
          'Mataasnakahoy',
          'Nasugbu',
          'Padre Garcia',
          'Rosario',
          'San Jose',
          'San Juan',
          'San Luis',
          'San Nicolas',
          'San Pascual',
          'Santa Teresita',
          'Santo Tomas',
          'Taal',
          'Talisay',
          'Tanauan City',
          'Taysan',
          'Tingloy',
          'Tuy',
        ],
      },
      {
        id: 'province-2',
        name: 'Cavite',
        citiesMunicipalities: [
          'Alfonso',
          'Amadeo',
          'Bacoor City',
          'Carmona',
          'Cavite City',
          'Dasmariñas City',
          'General Emilio Aguinaldo',
          'General Mariano Alvarez',
          'General Trias City',
          'Imus City',
          'Indang',
          'Kawit',
          'Magallanes',
          'Maragondon',
          'Mendez',
          'Naic',
          'Noveleta',
          'Rosario',
          'Silang',
          'Tagaytay City',
          'Tanza',
          'Ternate',
          'Trece Martires City',
        ],
      },
      {
        id: 'province-3',
        name: 'Laguna',
        citiesMunicipalities: [
          'Alaminos',
          'Bay',
          'Biñan City',
          'Cabuyao City',
          'Calamba City',
          'Calauan',
          'Cavinti',
          'Famy',
          'Kalayaan',
          'Liliw',
          'Los Baños',
          'Luisiana',
          'Lumban',
          'Mabitac',
          'Magdalena',
          'Majayjay',
          'Nagcarlan',
          'Paete',
          'Pagsanjan',
          'Pakil',
          'Pangil',
          'Pila',
          'Rizal',
          'San Pablo City',
          'San Pedro City',
          'Santa Cruz',
          'Santa Maria',
          'Santa Rosa City',
          'Siniloan',
          'Victoria',
        ],
      },
      {
        id: 'province-4',
        name: 'Quezon',
        citiesMunicipalities: [
          'Agdangan',
          'Alabat',
          'Atimonan',
          'Buenavista',
          'Burdeos',
          'Calauag',
          'Candelaria',
          'Catanauan',
          'Dolores',
          'General Luna',
          'General Nakar',
          'Guinayangan',
          'Gumaca',
          'Infanta',
          'Jomalig',
          'Lopez',
          'Lucban',
          'Lucena City',
          'Macalelon',
          'Mauban',
          'Mulanay',
          'Padre Burgos',
          'Pagbilao',
          'Panukulan',
          'Patnanungan',
          'Perez',
          'Pitogo',
          'Plaridel',
          'Polillo',
          'Quezon',
          'Real',
          'Sampaloc',
          'San Andres',
          'San Antonio',
          'San Francisco',
          'San Narciso',
          'Sariaya',
          'Tagkawayan',
          'Tayabas City',
          'Tiaong',
          'Unisan',
        ],
      },
      {
        id: 'province-5',
        name: 'Rizal',
        citiesMunicipalities: [
          'Angono',
          'Antipolo City',
          'Baras',
          'Binangonan',
          'Cainta',
          'Cardona',
          'Jala-Jala',
          'Morong',
          'Pililla',
          'Rodriguez',
          'San Mateo',
          'Tanay',
          'Taytay',
          'Teresa',
        ],
      },
      {
        id: 'province-6',
        name: 'Marinduque',
        citiesMunicipalities: [
          'Boac',
          'Buenavista',
          'Gasan',
          'Mogpog',
          'Santa Cruz',
          'Torrijos',
        ],
      },
      {
        id: 'province-7',
        name: 'Occidental Mindoro',
        citiesMunicipalities: [
          'Abra de Ilog',
          'Calintaan',
          'Looc',
          'Lubang',
          'Magsaysay',
          'Mamburao',
          'Paluan',
          'Rizal',
          'Sablayan',
          'San Jose',
          'Santa Cruz',
        ],
      },
      {
        id: 'province-8',
        name: 'Oriental Mindoro',
        citiesMunicipalities: [
          'Baco',
          'Bansud',
          'Bongabong',
          'Bulalacao',
          'Calapan City',
          'Gloria',
          'Mansalay',
          'Naujan',
          'Pinamalayan',
          'Pola',
          'Puerto Galera',
          'Roxas',
          'San Teodoro',
          'Socorro',
          'Victoria',
        ],
      },
      {
        id: 'province-9',
        name: 'Palawan',
        citiesMunicipalities: [
          'Aborlan',
          'Agutaya',
          'Araceli',
          'Balabac',
          'Bataraza',
          "Brooke's Point",
          'Busuanga',
          'Cagayancillo',
          'Coron',
          'Culion',
          'Cuyo',
          'Dumaran',
          'El Nido',
          'Kalayaan',
          'Linapacan',
          'Magsaysay',
          'Narra',
          'Puerto Princesa City',
          'Quezon',
          'Rizal',
          'Roxas',
          'San Vicente',
          'Sofronio Española',
          'Taytay',
        ],
      },
      {
        id: 'province-10',
        name: 'Romblon',
        citiesMunicipalities: [
          'Alcantara',
          'Banton',
          'Cajidiocan',
          'Calatrava',
          'Concepcion',
          'Corcuera',
          'Ferrol',
          'Looc',
          'Magdiwang',
          'Odiongan',
          'Romblon',
          'San Agustin',
          'San Andres',
          'San Fernando',
          'San Jose',
          'Santa Fe',
          'Santa Maria',
        ],
      },
    ],
  },
  {
    id: 'region-5',
    name: 'Bicol Region (Region V)',
    provinces: [
      {
        id: 'province-1',
        name: 'Albay',
        citiesMunicipalities: [
          'Bacacay',
          'Camalig',
          'Daraga',
          'Guinobatan',
          'Jovellar',
          'Legazpi City',
          'Libon',
          'Ligao City',
          'Malilipot',
          'Malinao',
          'Manito',
          'Oas',
          'Pio Duran',
          'Polangui',
          'Rapu-Rapu',
          'Santo Domingo',
          'Tabaco City',
          'Tiwi',
        ],
      },
      {
        id: 'province-2',
        name: 'Camarines Norte',
        citiesMunicipalities: [
          'Basud',
          'Capalonga',
          'Daet',
          'Jose Panganiban',
          'Labo',
          'Mercedes',
          'Paracale',
          'San Lorenzo Ruiz',
          'San Vicente',
          'Santa Elena',
          'Talisay',
          'Vinzons',
        ],
      },
      {
        id: 'province-3',
        name: 'Camarines Sur',
        citiesMunicipalities: [
          'Baao',
          'Balatan',
          'Bato',
          'Bombon',
          'Buhi',
          'Bula',
          'Cabusao',
          'Calabanga',
          'Camaligan',
          'Canaman',
          'Caramoan',
          'Del Gallego',
          'Gainza',
          'Garchitorena',
          'Goa',
          'Iriga City',
          'Lagonoy',
          'Libmanan',
          'Lupi',
          'Magarao',
          'Milaor',
          'Minalabac',
          'Nabua',
          'Naga City',
          'Ocampo',
          'Pamplona',
          'Pasacao',
          'Pili',
          'Presentacion',
          'Ragay',
          'Sagñay',
          'San Fernando',
          'San Jose',
          'Sipocot',
          'Siruma',
          'Tigaon',
          'Tinambac',
        ],
      },
      {
        id: 'province-4',
        name: 'Catanduanes',
        citiesMunicipalities: [
          'Bagamanoc',
          'Baras',
          'Bato',
          'Caramoran',
          'Gigmoto',
          'Pandan',
          'Panganiban',
          'San Andres',
          'San Miguel',
          'Viga',
          'Virac',
        ],
      },
      {
        id: 'province-5',
        name: 'Masbate',
        citiesMunicipalities: [
          'Aroroy',
          'Baleno',
          'Balud',
          'Batuan',
          'Cataingan',
          'Cawayan',
          'Claveria',
          'Dimasalang',
          'Esperanza',
          'Mandaon',
          'Masbate City',
          'Milagros',
          'Mobo',
          'Monreal',
          'Palanas',
          'Pio V. Corpuz',
          'Placer',
          'San Fernando',
          'San Jacinto',
          'San Pascual',
          'Uson',
        ],
      },
      {
        id: 'province-6',
        name: 'Sorsogon',
        citiesMunicipalities: [
          'Barcelona',
          'Bulan',
          'Bulusan',
          'Casiguran',
          'Castilla',
          'Donsol',
          'Gubat',
          'Irosin',
          'Juban',
          'Magallanes',
          'Matnog',
          'Pilar',
          'Prieto Diaz',
          'Santa Magdalena',
          'Sorsogon City',
        ],
      },
    ],
  },
  {
    id: 'region-6',
    name: 'Western Visayas (Region VI)',
    provinces: [
      {
        id: 'province-1',
        name: 'Aklan',
        citiesMunicipalities: [
          'Altavas',
          'Balete',
          'Banga',
          'Batan',
          'Buruanga',
          'Ibajay',
          'Kalibo',
          'Lezo',
          'Libacao',
          'Madalag',
          'Makato',
          'Malay',
          'Malinao',
          'Nabas',
          'New Washington',
          'Numancia',
          'Tangalan',
        ],
      },
      {
        id: 'province-2',
        name: 'Antique',
        citiesMunicipalities: [
          'Anini-y',
          'Barbaza',
          'Belison',
          'Bugasong',
          'Caluya',
          'Culasi',
          'Hamtic',
          'Laua-an',
          'Libertad',
          'Pandan',
          'Patnongon',
          'San Jose',
          'San Remigio',
          'Sebaste',
          'Sibalom',
          'Tibiao',
          'Tobias Fornier',
          'Valderrama',
        ],
      },
      {
        id: 'province-3',
        name: 'Capiz',
        citiesMunicipalities: [
          'Cuartero',
          'Dao',
          'Dumalag',
          'Dumarao',
          'Ivisan',
          'Jamindan',
          'Maayon',
          'Mambusao',
          'Panay',
          'Panitan',
          'Pilar',
          'Pontevedra',
          'President Roxas',
          'Roxas City',
          'Sapian',
          'Sigma',
          'Tapaz',
        ],
      },
      {
        id: 'province-4',
        name: 'Guimaras',
        citiesMunicipalities: [
          'Buenavista',
          'Jordan',
          'Nueva Valencia',
          'San Lorenzo',
          'Sibunag',
        ],
      },
      {
        id: 'province-5',
        name: 'Iloilo',
        citiesMunicipalities: [
          'Ajuy',
          'Alimodian',
          'Anilao',
          'Badiangan',
          'Balasan',
          'Banate',
          'Barotac Nuevo',
          'Barotac Viejo',
          'Batad',
          'Bingawan',
          'Cabatuan',
          'Calinog',
          'Carles',
          'Concepcion',
          'Dingle',
          'Dueñas',
          'Dumangas',
          'Estancia',
          'Guimbal',
          'Igbaras',
          'Iloilo City',
          'Janiuay',
          'Lambunao',
          'Leganes',
          'Lemery',
          'Leon',
          'Maasin',
          'Miagao',
          'Mina',
          'New Lucena',
          'Oton',
          'Passi City',
          'Pavia',
          'Pototan',
          'San Dionisio',
          'San Enrique',
          'San Joaquin',
          'San Miguel',
          'San Rafael',
          'Santa Barbara',
          'Sara',
          'Tigbauan',
          'Tubungan',
          'Zarraga',
        ],
      },
      {
        id: 'province-6',
        name: 'Negros Occidental',
        citiesMunicipalities: [
          'Bacolod City',
          'Bago City',
          'Binalbagan',
          'Cadiz City',
          'Calatrava',
          'Candoni',
          'Cauayan',
          'Enrique B. Magalona',
          'Escalante City',
          'Himamaylan City',
          'Hinigaran',
          'Hinoba-an',
          'Ilog',
          'Isabela',
          'Kabankalan City',
          'La Carlota City',
          'La Castellana',
          'Manapla',
          'Moises Padilla',
          'Murcia',
          'Pontevedra',
          'Pulupandan',
          'Sagay City',
          'Salvador Benedicto',
          'San Carlos City',
          'San Enrique',
          'Silay City',
          'Sipalay City',
          'Talisay City',
          'Toboso',
          'Valladolid',
          'Victorias City',
        ],
      },
    ],
  },
  {
    id: 'region-7',
    name: 'Central Visayas (Region VII)',
    provinces: [
      {
        id: 'province-1',
        name: 'Bohol',
        citiesMunicipalities: [
          'Alburquerque',
          'Alicia',
          'Anda',
          'Antequera',
          'Baclayon',
          'Balilihan',
          'Batuan',
          'Bien Unido',
          'Bilar',
          'Buenavista',
          'Calape',
          'Candijay',
          'Carmen',
          'Catigbian',
          'Clarin',
          'Corella',
          'Cortes',
          'Dagohoy',
          'Danao',
          'Dauis',
          'Dimiao',
          'Duero',
          'Garcia Hernandez',
          'Guindulman',
          'Inabanga',
          'Jagna',
          'Jetafe',
          'Lila',
          'Loay',
          'Loboc',
          'Loon',
          'Mabini',
          'Maribojoc',
          'Panglao',
          'Pilar',
          'President Carlos P. Garcia',
          'Sagbayan',
          'San Isidro',
          'San Miguel',
          'Sevilla',
          'Sierra Bullones',
          'Sikatuna',
          'Tagbilaran City',
          'Talibon',
          'Trinidad',
          'Tubigon',
          'Ubay',
          'Valencia',
        ],
      },
      {
        id: 'province-2',
        name: 'Cebu',
        citiesMunicipalities: [
          'Alcantara',
          'Alcoy',
          'Alegria',
          'Aloguinsan',
          'Argao',
          'Asturias',
          'Badian',
          'Balamban',
          'Bantayan',
          'Barili',
          'Bogo City',
          'Boljoon',
          'Borbon',
          'Carcar City',
          'Carmen',
          'Catmon',
          'Cebu City',
          'Compostela',
          'Consolacion',
          'Cordova',
          'Daanbantayan',
          'Dalaguete',
          'Danao City',
          'Ginatilan',
          'Lapu-Lapu City',
          'Liloan',
          'Madridejos',
          'Malabuyoc',
          'Mandaue City',
          'Medellin',
          'Minglanilla',
          'Moalboal',
          'Naga City',
          'Oslob',
          'Pilar',
          'Pinamungajan',
          'Poro',
          'Ronda',
          'Samboan',
          'San Fernando',
          'San Francisco',
          'San Remigio',
          'Santa Fe',
          'Santander',
          'Sibonga',
          'Sogod',
          'Tabogon',
          'Tabuelan',
          'Talisay City',
          'Toledo City',
          'Tuburan',
          'Tudela',
        ],
      },
      {
        id: 'province-3',
        name: 'Negros Oriental',
        citiesMunicipalities: [
          'Amlan',
          'Ayungon',
          'Bacong',
          'Bais City',
          'Basay',
          'Bayawan City',
          'Bindoy',
          'Canlaon City',
          'Dauin',
          'Dumaguete City',
          'Guihulngan City',
          'Jimalalud',
          'La Libertad',
          'Mabinay',
          'Manjuyod',
          'Pamplona',
          'San Jose',
          'Santa Catalina',
          'Siaton',
          'Sibulan',
          'Tanjay City',
          'Tayasan',
          'Valencia',
          'Vallehermoso',
          'Zamboanguita',
        ],
      },
      {
        id: 'province-4',
        name: 'Siquijor',
        citiesMunicipalities: [
          'Enrique Villanueva',
          'Larena',
          'Lazi',
          'Maria',
          'San Juan',
          'Siquijor',
        ],
      },
    ],
  },
  {
    id: 'region-8',
    name: 'Eastern Visayas (Region VIII)',
    provinces: [
      {
        id: 'province-1',
        name: 'Biliran',
        citiesMunicipalities: [
          'Almeria',
          'Biliran',
          'Cabucgayan',
          'Caibiran',
          'Culaba',
          'Kawayan',
          'Maripipi',
          'Naval',
        ],
      },
      {
        id: 'province-2',
        name: 'Eastern Samar',
        citiesMunicipalities: [
          'Arteche',
          'Balangiga',
          'Balangkayan',
          'Borongan City',
          'Can-avid',
          'Dolores',
          'General MacArthur',
          'Giporlos',
          'Guiuan',
          'Hernani',
          'Jipapad',
          'Lawaan',
          'Llorente',
          'Maslog',
          'Maydolong',
          'Mercedes',
          'Oras',
          'Quinapondan',
          'Salcedo',
          'San Julian',
          'San Policarpo',
          'Sulat',
          'Taft',
        ],
      },
      {
        id: 'province-3',
        name: 'Leyte',
        citiesMunicipalities: [
          'Abuyog',
          'Alangalang',
          'Albuera',
          'Babatngon',
          'Barugo',
          'Bato',
          'Baybay City',
          'Burauen',
          'Calubian',
          'Capoocan',
          'Carigara',
          'Dagami',
          'Dulag',
          'Hilongos',
          'Hindang',
          'Inopacan',
          'Isabel',
          'Jaro',
          'Javier',
          'Julita',
          'Kananga',
          'La Paz',
          'Leyte',
          'MacArthur',
          'Mahaplag',
          'Matag-ob',
          'Matalom',
          'Mayorga',
          'Merida',
          'Ormoc City',
          'Palo',
          'Palompon',
          'Pastrana',
          'San Isidro',
          'San Miguel',
          'Santa Fe',
          'Tabango',
          'Tabontabon',
          'Tacloban City',
          'Tanauan',
          'Tolosa',
          'Tunga',
          'Villaba',
        ],
      },
      {
        id: 'province-4',
        name: 'Northern Samar',
        citiesMunicipalities: [
          'Allen',
          'Biri',
          'Bobon',
          'Capul',
          'Catarman',
          'Catubig',
          'Gamay',
          'Laoang',
          'Lapinig',
          'Las Navas',
          'Lavezares',
          'Mapanas',
          'Mondragon',
          'Palapag',
          'Pambujan',
          'Rosario',
          'San Antonio',
          'San Isidro',
          'San Jose',
          'San Roque',
          'San Vicente',
          'Silvino Lobos',
          'Victoria',
        ],
      },
      {
        id: 'province-5',
        name: 'Samar (Western Samar)',
        citiesMunicipalities: [
          'Almagro',
          'Basey',
          'Calbayog City',
          'Calbiga',
          'Catbalogan City',
          'Daram',
          'Gandara',
          'Hinabangan',
          'Jiabong',
          'Marabut',
          'Matuguinao',
          'Motiong',
          'Pagsanghan',
          'Paranas',
          'Pinabacdao',
          'San Jorge',
          'San Jose de Buan',
          'San Sebastian',
          'Santa Margarita',
          'Santa Rita',
          'Santo Niño',
          'Tagapul-an',
          'Talalora',
          'Tarangnan',
          'Villareal',
          'Zumarraga',
        ],
      },
      {
        id: 'province-6',
        name: 'Southern Leyte',
        citiesMunicipalities: [
          'Anahawan',
          'Bontoc',
          'Hinunangan',
          'Hinundayan',
          'Libagon',
          'Liloan',
          'Limasawa',
          'Maasin City',
          'Macrohon',
          'Malitbog',
          'Padre Burgos',
          'Pintuyan',
          'Saint Bernard',
          'San Francisco',
          'San Juan',
          'Silago',
          'Sogod',
          'Tomas Oppus',
        ],
      },
    ],
  },
  {
    id: 'region-9',
    name: 'Zamboanga Peninsula (Region IX)',
    provinces: [
      {
        id: 'province-1',
        name: 'Zamboanga del Norte',
        citiesMunicipalities: [
          'Bacungan',
          'Baliguian',
          'Dapitan City',
          'Dipolog City',
          'Godod',
          'Gutalac',
          'Jose Dalman',
          'Kalawit',
          'Katipunan',
          'La Libertad',
          'Labason',
          'Liloy',
          'Manukan',
          'Mutia',
          'Piñan',
          'Polanco',
          'Pres. Manuel A. Roxas',
          'Rizal',
          'Salug',
          'Sergio Osmeña Sr.',
          'Siayan',
          'Sibuco',
          'Sibutad',
          'Sindangan',
          'Siocon',
          'Sirawai',
          'Tampilisan',
        ],
      },
      {
        id: 'province-2',
        name: 'Zamboanga del Sur',
        citiesMunicipalities: [
          'Aurora',
          'Bayog',
          'Dimataling',
          'Dinas',
          'Dumalinao',
          'Dumingag',
          'Guipos',
          'Josefina',
          'Kumalarang',
          'Labangan',
          'Lakewood',
          'Lapuyan',
          'Mahayag',
          'Margosatubig',
          'Midsalip',
          'Molave',
          'Pagadian City',
          'Pitogo',
          'Ramon Magsaysay',
          'San Miguel',
          'San Pablo',
          'Sominot',
          'Tabina',
          'Tambulig',
          'Tigbao',
          'Tukuran',
          'Vincenzo A. Sagun',
          'Zamboanga City',
        ],
      },
      {
        id: 'province-3',
        name: 'Zamboanga Sibugay',
        citiesMunicipalities: [
          'Alicia',
          'Buug',
          'Diplahan',
          'Imelda',
          'Ipil',
          'Kabasalan',
          'Mabuhay',
          'Malangas',
          'Naga',
          'Olutanga',
          'Payao',
          'Roseller T. Lim',
          'Siay',
          'Talusan',
          'Titay',
          'Tungawan',
        ],
      },
    ],
  },
  {
    id: 'region-10',
    name: 'Northern Mindanao (Region X)',
    provinces: [
      {
        id: 'province-1',
        name: 'Bukidnon',
        citiesMunicipalities: [
          'Baungon',
          'Cabanglasan',
          'Damulog',
          'Dangcagan',
          'Don Carlos',
          'Impasugong',
          'Kadingilan',
          'Kalilangan',
          'Kibawe',
          'Kitaotao',
          'Lantapan',
          'Libona',
          'Malaybalay City',
          'Malitbog',
          'Manolo Fortich',
          'Maramag',
          'Pangantucan',
          'Quezon',
          'San Fernando',
          'Sumilao',
          'Talakag',
          'Valencia City',
        ],
      },
      {
        id: 'province-2',
        name: 'Camiguin',
        citiesMunicipalities: [
          'Catarman',
          'Guinsiliban',
          'Mahinog',
          'Mambajao',
          'Sagay',
        ],
      },
      {
        id: 'province-3',
        name: 'Lanao del Norte',
        citiesMunicipalities: [
          'Bacolod',
          'Baloi',
          'Baroy',
          'Iligan City',
          'Kapatagan',
          'Kauswagan',
          'Kolambugan',
          'Lala',
          'Linamon',
          'Magsaysay',
          'Maigo',
          'Matungao',
          'Munai',
          'Nunungan',
          'Pantao Ragat',
          'Pantar',
          'Poona Piagapo',
          'Salvador',
          'Sapad',
          'Sultan Naga Dimaporo',
          'Tagoloan',
          'Tangcal',
          'Tubod',
        ],
      },
      {
        id: 'province-4',
        name: 'Misamis Occidental',
        citiesMunicipalities: [
          'Aloran',
          'Baliangao',
          'Bonifacio',
          'Calamba',
          'Clarin',
          'Concepcion',
          'Don Victoriano Chiongbian',
          'Jimenez',
          'Lopez Jaena',
          'Oroquieta City',
          'Ozamiz City',
          'Panaon',
          'Plaridel',
          'Sapang Dalaga',
          'Sinacaban',
          'Tangub City',
          'Tudela',
        ],
      },
      {
        id: 'province-5',
        name: 'Misamis Oriental',
        citiesMunicipalities: [
          'Alubijid',
          'Balingasag',
          'Balingoan',
          'Binuangan',
          'Cagayan de Oro City',
          'Claveria',
          'El Salvador City',
          'Gingoog City',
          'Gitagum',
          'Initao',
          'Jasaan',
          'Kinoguitan',
          'Lagonglong',
          'Laguindingan',
          'Libertad',
          'Lugait',
          'Magsaysay',
          'Manticao',
          'Medina',
          'Naawan',
          'Opol',
          'Salay',
          'Sugbongcogon',
          'Tagoloan',
          'Talisayan',
          'Villanueva',
        ],
      },
    ],
  },
  {
    id: 'region-11',
    name: 'Davao Region (Region XI)',
    provinces: [
      {
        id: 'province-1',
        name: 'Davao de Oro',
        citiesMunicipalities: [
          'Compostela',
          'Laak',
          'Mabini',
          'Maco',
          'Maragusan',
          'Mawab',
          'Monkayo',
          'Montevista',
          'Nabunturan',
          'New Bataan',
          'Pantukan',
        ],
      },
      {
        id: 'province-2',
        name: 'Davao del Norte',
        citiesMunicipalities: [
          'Asuncion',
          'Braulio E. Dujali',
          'Carmen',
          'Kapalong',
          'New Corella',
          'Panabo City',
          'Samal City',
          'San Isidro',
          'Santo Tomas',
          'Tagum City',
          'Talaingod',
        ],
      },
      {
        id: 'province-3',
        name: 'Davao del Sur',
        citiesMunicipalities: [
          'Bansalan',
          'Davao City',
          'Digos City',
          'Hagonoy',
          'Kiblawan',
          'Magsaysay',
          'Malalag',
          'Matanao',
          'Padada',
          'Santa Cruz',
          'Sulop',
        ],
      },
      {
        id: 'province-4',
        name: 'Davao Occidental',
        citiesMunicipalities: [
          'Don Marcelino',
          'Jose Abad Santos',
          'Malita',
          'Santa Maria',
          'Sarangani',
        ],
      },
      {
        id: 'province-5',
        name: 'Davao Oriental',
        citiesMunicipalities: [
          'Baganga',
          'Banaybanay',
          'Boston',
          'Caraga',
          'Cateel',
          'Governor Generoso',
          'Lupon',
          'Manay',
          'Mati City',
          'San Isidro',
          'Tarragona',
        ],
      },
    ],
  },
  {
    id: 'region-12',
    name: 'Soccsksargen (Region XII)',
    provinces: [
      {
        id: 'province-1',
        name: 'Cotabato (North Cotabato)',
        citiesMunicipalities: [
          'Alamada',
          'Aleosan',
          'Antipas',
          'Arakan',
          'Banisilan',
          'Carmen',
          'Kabacan',
          'Kidapawan City',
          'Libungan',
          'Magpet',
          'Makilala',
          'Matalam',
          'Midsayap',
          'Pigcawayan',
          'Pikit',
          'President Roxas',
          'Tulunan',
        ],
      },
      {
        id: 'province-2',
        name: 'Sarangani',
        citiesMunicipalities: [
          'Alabel',
          'Glan',
          'Kiamba',
          'Maasim',
          'Maitum',
          'Malapatan',
          'Malungon',
        ],
      },
      {
        id: 'province-3',
        name: 'South Cotabato',
        citiesMunicipalities: [
          'Banga',
          'General Santos City',
          'Koronadal City',
          'Lake Sebu',
          'Norala',
          'Polomolok',
          'Santo Niño',
          'Surallah',
          'Tampakan',
          'Tantangan',
          'Tupi',
        ],
      },
      {
        id: 'province-4',
        name: 'Sultan Kudarat',
        citiesMunicipalities: [
          'Bagumbayan',
          'Columbio',
          'Esperanza',
          'Isulan',
          'Kalamansig',
          'Lambayong',
          'Lebak',
          'Lutayan',
          'Palimbang',
          'President Quirino',
          'Senator Ninoy Aquino',
          'Tacurong City',
        ],
      },
    ],
  },
  {
    id: 'region-13',
    name: 'Caraga (Region XIII)',
    provinces: [
      {
        id: 'province-1',
        name: 'Agusan del Norte',
        citiesMunicipalities: [
          'Buenavista',
          'Butuan City',
          'Cabadbaran City',
          'Carmen',
          'Jabonga',
          'Kitcharao',
          'Las Nieves',
          'Magallanes',
          'Nasipit',
          'Remedios T. Romualdez',
          'Santiago',
          'Tubay',
        ],
      },
      {
        id: 'province-2',
        name: 'Agusan del Sur',
        citiesMunicipalities: [
          'Bayugan City',
          'Bunawan',
          'Esperanza',
          'La Paz',
          'Loreto',
          'Prosperidad',
          'Rosario',
          'San Francisco',
          'San Luis',
          'Santa Josefa',
          'Sibagat',
          'Talacogon',
          'Trento',
          'Veruela',
        ],
      },
      {
        id: 'province-3',
        name: 'Dinagat Islands',
        citiesMunicipalities: [
          'Basilisa',
          'Cagdianao',
          'Dinagat',
          'Libjo',
          'Loreto',
          'San Jose',
          'Tubajon',
        ],
      },
      {
        id: 'province-4',
        name: 'Surigao del Norte',
        citiesMunicipalities: [
          'Alegria',
          'Bacuag',
          'Burgos',
          'Claver',
          'Dapa',
          'Del Carmen',
          'General Luna',
          'Gigaquit',
          'Mainit',
          'Malimono',
          'Pilar',
          'Placer',
          'San Benito',
          'San Francisco',
          'San Isidro',
          'Santa Monica',
          'Sison',
          'Socorro',
          'Surigao City',
          'Tagana-an',
          'Tubod',
        ],
      },
      {
        id: 'province-5',
        name: 'Surigao del Sur',
        citiesMunicipalities: [
          'Barobo',
          'Bayabas',
          'Bislig City',
          'Cagwait',
          'Cantilan',
          'Carmen',
          'Carrascal',
          'Cortes',
          'Hinatuan',
          'Lanuza',
          'Lianga',
          'Lingig',
          'Madrid',
          'Marihatag',
          'San Agustin',
          'San Miguel',
          'Tagbina',
          'Tago',
          'Tandag City',
        ],
      },
    ],
  },
  {
    id: 'region-14',
    name: 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)',
    provinces: [
      {
        id: 'province-1',
        name: 'Basilan',
        citiesMunicipalities: [
          'Akbar',
          'Al-Barka',
          'Hadji Mohammad Ajul',
          'Hadji Muhtamad',
          'Isabela City',
          'Lamitan City',
          'Lantawan',
          'Maluso',
          'Sumisip',
          'Tabuan-Lasa',
          'Tipo-Tipo',
          'Tuburan',
          'Ungkaya Pukan',
        ],
      },
      {
        id: 'province-2',
        name: 'Lanao del Sur',
        citiesMunicipalities: [
          'Bacolod-Kalawi',
          'Balabagan',
          'Balindong',
          'Bayang',
          'Binidayan',
          'Buadiposo-Buntong',
          'Bubong',
          'Butig',
          'Calanogas',
          'Ditsaan-Ramain',
          'Ganassi',
          'Kapai',
          'Kapatagan',
          'Lumba-Bayabao',
          'Lumbaca-Unayan',
          'Lumbatan',
          'Lumbayanague',
          'Madalum',
          'Madamba',
          'Maguing',
          'Malabang',
          'Marantao',
          'Marawi City',
          'Marogong',
          'Masiu',
          'Mulondo',
          'Pagayawan',
          'Piagapo',
          'Poona Bayabao',
          'Pualas',
          'Saguiaran',
          'Sultan Dumalondong',
          'Tagoloan II',
          'Tamparan',
          'Taraka',
          'Tubaran',
          'Tugaya',
          'Wao',
        ],
      },
      {
        id: 'province-3',
        name: 'Maguindanao del Norte',
        citiesMunicipalities: [
          'Barira',
          'Buldon',
          'Datu Blah T. Sinsuat',
          'Datu Odin Sinsuat',
          'Kabuntalan',
          'Matanog',
          'Parang',
          'Sultan Kudarat',
          'Sultan Mastura',
          'Upi',
        ],
      },
      {
        id: 'province-4',
        name: 'Maguindanao del Sur',
        citiesMunicipalities: [
          'Ampatuan',
          'Buluan',
          'Datu Abdullah Sangki',
          'Datu Anggal Midtimbang',
          'Datu Hoffer Ampatuan',
          'Datu Montawal',
          'Datu Paglas',
          'Datu Piang',
          'Datu Salibo',
          'Datu Saudi-Ampatuan',
          'Datu Unsay',
          'Gen. S. K. Pendatun',
          'Guindulungan',
          'Mamasapano',
          'Mangudadatu',
          'Pagalungan',
          'Paglat',
          'Pandag',
          'Rajah Buayan',
          'Shariff Aguak',
          'Shariff Saydona Mustapha',
          'South Upi',
          'Sultan Sa Barongis',
          'Talayan',
          'Talitay',
        ],
      },
      {
        id: 'province-5',
        name: 'Sulu',
        citiesMunicipalities: [
          'Hadji Panglima Tahil',
          'Indanan',
          'Jolo',
          'Kalingalan Caluang',
          'Lugus',
          'Luuk',
          'Maimbung',
          'Old Panamao',
          'Omar',
          'Pandami',
          'Panglima Estino',
          'Pangutaran',
          'Parang',
          'Pata',
          'Patikul',
          'Siasi',
          'Talipao',
          'Tapul',
          'Tongkil',
        ],
      },
      {
        id: 'province-6',
        name: 'Tawi-Tawi',
        citiesMunicipalities: [
          'Bongao',
          'Languyan',
          'Mapun',
          'Panglima Sugala',
          'Sapa-Sapa',
          'Sibutu',
          'Simunul',
          'Sitangkai',
          'South Ubian',
          'Tandubas',
          'Turtle Islands',
        ],
      },
    ],
  },
  {
    id: 'region-15',
    name: 'Cordillera Administrative Region (CAR)',
    provinces: [
      {
        id: 'province-1',
        name: 'Abra',
        citiesMunicipalities: [
          'Bangued',
          'Boliney',
          'Bucay',
          'Bucloc',
          'Daguioman',
          'Danglas',
          'Dolores',
          'La Paz',
          'Lacub',
          'Lagangilang',
          'Lagayan',
          'Langiden',
          'Licuan-Baay',
          'Luba',
          'Malibcong',
          'Manabo',
          'Peñarrubia',
          'Pidigan',
          'Pilar',
          'Sallapadan',
          'San Isidro',
          'San Juan',
          'San Quintin',
          'Tayum',
          'Tineg',
          'Tubo',
          'Villaviciosa',
        ],
      },
      {
        id: 'province-2',
        name: 'Apayao',
        citiesMunicipalities: [
          'Calanasan',
          'Conner',
          'Flora',
          'Kabugao',
          'Luna',
          'Pudtol',
          'Santa Marcela',
        ],
      },
      {
        id: 'province-3',
        name: 'Benguet',
        citiesMunicipalities: [
          'Atok',
          'Bakun',
          'Bokod',
          'Buguias',
          'Itogon',
          'Kabayan',
          'Kapangan',
          'Kibungan',
          'La Trinidad',
          'Mankayan',
          'Sablan',
          'Tuba',
          'Tublay',
        ],
      },
      {
        id: 'province-4',
        name: 'Ifugao',
        citiesMunicipalities: [
          'Aguinaldo',
          'Alfonso Lista',
          'Asipulo',
          'Banaue',
          'Hingyon',
          'Hungduan',
          'Kiangan',
          'Lagawe',
          'Lamut',
          'Mayoyao',
          'Tinoc',
        ],
      },
      {
        id: 'province-5',
        name: 'Kalinga',
        citiesMunicipalities: [
          'Balbalan',
          'Lubuagan',
          'Pasil',
          'Pinukpuk',
          'Rizal',
          'Tabuk City',
          'Tanudan',
          'Tinglayan',
        ],
      },
      {
        id: 'province-6',
        name: 'Mountain Province',
        citiesMunicipalities: [
          'Barlig',
          'Bauko',
          'Besao',
          'Bontoc',
          'Natonin',
          'Paracelis',
          'Sabangan',
          'Sadanga',
          'Sagada',
          'Tadian',
        ],
      },
    ],
  },
  {
    id: 'region-16',
    name: 'National Capital Region (NCR)',
    provinces: [
      {
        id: 'province-1',
        name: 'Metro Manila',
        citiesMunicipalities: [
          'Caloocan City',
          'Las Piñas City',
          'Makati City',
          'Malabon City',
          'Mandaluyong City',
          'Manila City',
          'Marikina City',
          'Muntinlupa City',
          'Navotas City',
          'Parañaque City',
          'Pasay City',
          'Pasig City',
          'Quezon City',
          'San Juan City',
          'Taguig City',
          'Valenzuela City',
          'Pateros',
        ],
      },
    ],
  },
];
